//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_EmployeesAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string FullName { get; set; }
        public System.DateTime Birthday { get; set; }
        public System.DateTime DateOfEmployement { get; set; }
        public string Division { get; set; }
        public string TIN { get; set; }
        public int TabNum { get; set; }
        public int positionID { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
