//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_EmployeesAccounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public int orderID { get; set; }
        public System.DateTime date { get; set; }
        public string Comment { get; set; }
        public string Name { get; set; }
    
        public virtual orderType orderType { get; set; }
    }
}
